service: foodiary-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs22.x
  architecture: arm64

package:
  individually: true

build:
  esbuild:
    minify: true
    sourcemap: false

functions:
  signin:
    handler: src/functions/signin.handler
    events:
      - httpApi:
          path: /signin
          method: POST
  
  signUP:
    handler: src/functions/signup.handler
    events:
      - httpApi:
          path: /signup
          method: get


